backend/config/routes.rb
Rails.application.routes.draw do
  
  resources :charity_organizations
  resources :categories
  resources :preferences, only: [:index]
  resources :sessions, only: [:create, :destroy]
  get "discover" => "charity_organizations#discover", as: "discover"

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

backend/app/models/preference.rb
class Preference < ApplicationRecord
	has_and_belongs_to_many :users
	belongs_to :category
	has_many :charity_organizations
end

backend/app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :authorize
  before_action :set_preference, only: [:show, :edit, :update, :destroy]

  # GET /preferences
  # GET /preferences.json
  def index
    @preferences = Preference.all
    respond_to do |format|
      format.json {render json: @preferences.map { |pref| [pref.name, pref.id, pref.user_ids] } }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preference
      @preference = Preference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preference_params
      params.require(:preference).permit(:name)
    end
end

backend/app/helpers/preferences_helper.rb
module PreferencesHelper
end

backend/app/views/preferences/_form.html.erb
<%= form_with(model: preference, local: true) do |form| %>
  <% if preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(preference.errors.count, "error") %> prohibited this preference from being saved:</h2>

      <ul>
      <% preference.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :preference_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/preferences/edit.html.erb
<h1>Editing Preference</h1>

<%= render 'form', preference: @preference %>

<%= link_to 'Show', @preference %> |
<%= link_to 'Back', preferences_path %>

backend/app/views/preferences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Preferences</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @preferences.each do |preference| %>
      <tr>
        <td><%= preference.name %></td>
        <td><%= link_to 'Show', preference %></td>
        <td><%= link_to 'Edit', edit_preference_path(preference) %></td>
        <td><%= link_to 'Destroy', preference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Preference', new_preference_path %>

backend/app/views/preferences/new.html.erb
<h1>New Preference</h1>

<%= render 'form', preference: @preference %>

<%= link_to 'Back', preferences_path %>

backend/app/views/preferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @preference.name %>
</p>

<%= link_to 'Edit', edit_preference_path(@preference) %> |
<%= link_to 'Back', preferences_path %>