backend/config/routes.rb
Rails.application.routes.draw do
  
  resources :charity_organizations
  resources :categories
  resources :preferences, only: [:index]
  resources :sessions, only: [:create, :destroy]
  get "discover" => "charity_organizations#discover", as: "discover"

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

backend/app/models/charity_organization.rb
class CharityOrganization < ApplicationRecord
	belongs_to :preference
	def self.get_from_cache_or_fetch(user)
		# organizations we don't have cached
		fetch_ids = []
		# populate a list of preferences to fetch
		user.preferences.each do |pref|
			if pref.charity_organizations.blank?
				fetch_ids << [pref.charity_api_id, pref.id]
			end
		end
		# if any, fetch from api
		if fetch_ids.any?
			self.fetch_by_cause(fetch_ids)
		end
		# compile a list of organizations that fits preferences
		@charities = CharityOrganization.where(preference_id: user.preferences.pluck(:id))
	end

	def self.fetch_by_cause(ids)
		ids.each do |id|
			uri = 'https://api.data.charitynavigator.org/v2/Organizations?app_id=f942e24b&app_key=e1fdeddeb32086f78fe5e34495bdee79&causeID=' + id[0].to_s
			response = RestClient.get uri
			JSON.parse(response.body).each do |org|
				CharityOrganization.create(name: org["charityName"], 
										   preference_id: id[1], 
										   mission: org["mission"],
										   website: org["websiteURL"],
										   charity_api_id: org["orgID"],
										   trustworthiness: org["currentRating"]["score"])
			end
		end
	end
end

backend/app/controllers/charity_organizations_controller.rb
class CharityOrganizationsController < ApplicationController
  before_action :authorize

  def index
  		user = User.find_by(temp_token: params[:token])
		if user.blank?
  			respond_to do |format|
  				format.json { render json: :forbidden }
  			end
		else
    			@charities = CharityOrganization.get_from_cache_or_fetch(user).limit(10)
    			respond_to do |format|
      				format.json { render json: @charities.as_json(only: [:name, :website, :mission, :trustworthiness])}
    			end
		end
	end

  def discover
    ids = CharityOrganization.pluck(:id)
    max = ids.max
    min = ids.min
    @charities = []
    5.times do
      @charities << CharityOrganization.where(id: rand(min..max)).first
    end
    respond_to do |format|
      format.json { render json: @charities }
    end
  end
end

backend/app/helpers/charity_organizations_helper.rb
module CharityOrganizationsHelper
end

backend/app/views/charity_organizations/_form.html.erb
<%= form_with(model: charity_organization, local: true) do |form| %>
  <% if charity_organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(charity_organization.errors.count, "error") %> prohibited this charity_organization from being saved:</h2>

      <ul>
      <% charity_organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :charity_organization_name %>
  </div>

  <div class="field">
    <%= form.label :cause_id %>
    <%= form.text_field :cause_id, id: :charity_organization_cause_id %>
  </div>

  <div class="field">
    <%= form.label :mission %>
    <%= form.text_area :mission, id: :charity_organization_mission %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website, id: :charity_organization_website %>
  </div>

  <div class="field">
    <%= form.label :charity_api_id %>
    <%= form.text_field :charity_api_id, id: :charity_organization_charity_api_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/charity_organizations/edit.html.erb
<h1>Editing Charity Organization</h1>

<%= render 'form', charity_organization: @charity_organization %>

<%= link_to 'Show', @charity_organization %> |
<%= link_to 'Back', charity_organizations_path %>

backend/app/views/charity_organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Charity Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cause</th>
      <th>Mission</th>
      <th>Website</th>
      <th>Charity api</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charity_organizations.each do |charity_organization| %>
      <tr>
        <td><%= charity_organization.name %></td>
        <td><%= charity_organization.cause_id %></td>
        <td><%= charity_organization.mission %></td>
        <td><%= charity_organization.website %></td>
        <td><%= charity_organization.charity_api_id %></td>
        <td><%= link_to 'Show', charity_organization %></td>
        <td><%= link_to 'Edit', edit_charity_organization_path(charity_organization) %></td>
        <td><%= link_to 'Destroy', charity_organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charity Organization', new_charity_organization_path %>

backend/app/views/charity_organizations/new.html.erb
<h1>New Charity Organization</h1>

<%= render 'form', charity_organization: @charity_organization %>

<%= link_to 'Back', charity_organizations_path %>

backend/app/views/charity_organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @charity_organization.name %>
</p>

<p>
  <strong>Cause:</strong>
  <%= @charity_organization.cause_id %>
</p>

<p>
  <strong>Mission:</strong>
  <%= @charity_organization.mission %>
</p>

<p>
  <strong>Website:</strong>
  <%= @charity_organization.website %>
</p>

<p>
  <strong>Charity api:</strong>
  <%= @charity_organization.charity_api_id %>
</p>

<%= link_to 'Edit', edit_charity_organization_path(@charity_organization) %> |
<%= link_to 'Back', charity_organizations_path %>