backend/config/routes.rb
Rails.application.routes.draw do
  
  resources :charity_organizations
  resources :categories
  resources :preferences, only: [:index]
  resources :sessions, only: [:create, :destroy]
  get "discover" => "charity_organizations#discover", as: "discover"

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

backend/app/models/user.rb
class User < ApplicationRecord
	attr_accessor :password
	validates_presence_of :email, on: :create
	validates_presence_of :password, on: :create
	validates_confirmation_of :password
	validates_uniqueness_of :email
	before_save :downcase_email
	before_create :hash_password
	before_create :assign_causes
	validate :password_format, on: :create
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, length: { maximum: 255 }, uniqueness: { case_sensitive: false }, 
                                        format: { with: VALID_EMAIL_REGEX }
    has_and_belongs_to_many :preferences


	

	def generate_token
		self.temp_token = BCrypt::Engine.generate_salt
		self.temp_created = Date.today
		self.save(validate:false)
	end

	def assign_causes
		ids = []
		prefs = Preference.pluck(:id)
		ids[0] = prefs.sample
		ids[1] = prefs.sample
		self.preference_ids = ids
	end

	def expired_token?
		self.temp_created + 1.days < Date.today
	end

	def token_mismatch?(token)
		self.temp_token != token
	end

	private

	

	def downcase_email
		self.email = self.email.downcase 
	end

	def password_format
		if password.blank?
			errors.add :base, "Password field may not be empty"
		end
	end

	def hash_password
        if password.present?
            self.password_salt = BCrypt::Engine.generate_salt
            self.password_hash = User.digest(password,password_salt)
        end
    end

    def User.digest(string, salt=nil)
        if !salt
            salt = BCrypt::Engine.generate_salt
        end
            hashed_string = BCrypt::Engine.hash_secret(string, salt)
    end


    def self.authenticate(email,password)
        user = find_by_email(email.downcase)
        if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
            user
        else
            nil
        end
    end


end

backend/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:index, :update]

  # GET /users
  # GET /users.json
  def index
    respond_to do |format|
      format.json { "good job, you made it!"}
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.json { render json: :ok }
      else
        format.json { render json: @user.errors.to_json}
      end
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        @user.generate_token
        format.json { render json: @user.as_json(only: [:temp_token, :id]), status: :ok }
      else
        format.json { render json: @user.errors }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /users/1
  # # DELETE /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, preference_ids: [])
    end
end

backend/app/helpers/users_helper.rb
module UsersHelper
end

backend/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password_hash %>
    <%= form.text_field :password_hash, id: :user_password_hash %>
  </div>

  <div class="field">
    <%= form.label :password_salt %>
    <%= form.text_field :password_salt, id: :user_password_salt %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

backend/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password hash</th>
      <th>Password salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password_hash %></td>
        <td><%= user.password_salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

backend/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

backend/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password hash:</strong>
  <%= @user.password_hash %>
</p>

<p>
  <strong>Password salt:</strong>
  <%= @user.password_salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>